apiVersion: v1
kind: ConfigMap
metadata:
  name: github-workflow-config
  namespace: app
data:
  GITHUB_ORG: sktrinh12
  GITHUB_REPO: update-chromadb
  GITHUB_WORKFLOW_FILE: update-chromadb.yml
  GITHUB_BRANCH: main
